---
apiVersion: v1
kind: Deployment
metadata:
  name: "hop-deployment"
  labels:
    app: "hop"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hop"
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: hop
    spec:
      volumes:
      - name: hop-tls
        secret:
          secretName: hop-tls
      containers:
      - image: smartptr/hop:latest
        name: "hop"
        command:
        - /main
        args:
        - "--cacert"
        - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - "--cert"
        - /etc/tls/private/tls.crt
        - "--key"
        - /etc/tls/private/tls.key
        - "--interface"
        - 0.0.0.0
        - "--port_http"
        - "8000"
        - "--port_https"
        - "8443"
        - "--port_metrics"
        - "8080"
        volumeMounts:
        - name: "hop-tls"
          mountPath: "/etc/tls/private"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/port: "8080"
  labels:
    app: hop
    name: "hop"
  name: "hop"
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8000
  - port: 443
    name: https
    protocol: TCP
    targetPort: 8443
  - port: 8080
    name: prometheus
    protocol: TCP
    targetPort: 8080
  selector:
    name: "hop"
  sessionAffinity: None
  type: ClusterIP

